name: AudioLabSplitterMac
options:
  minimumXcodeGenVersion: 2.38.0
settings:
  base:
    PRODUCT_BUNDLE_IDENTIFIER: com.vanmobe.audiolab.splitter
    SWIFT_VERSION: 6.0
    MACOSX_DEPLOYMENT_TARGET: 13.0
targets:
  AudioLabSplitterMac:
    type: application
    platform: macOS
    deploymentTarget: "13.0"
    sources:
      - path: MoisesLocalMac
    settings:
      base:
        PRODUCT_NAME: AudioLabSplitterMac
        INFOPLIST_KEY_CFBundleDisplayName: AudioLabSplitterMac
        INFOPLIST_KEY_NSHumanReadableCopyright: Copyright © 2026
    dependencies:
      - sdk: libsqlite3.tbd
scheme:
  AudioLabSplitterMac:
    build:
      targets:
        AudioLabSplitterMac: all
    run:
      config: Debug
